#!/bin/bash

# set -x

. .bashrc

function get_dev() {
     pip install -r requirements_dev.txt
     pip install -r requirements_test.txt
}

echo "arguments are: "$1

case $1 in
    start)
        echo "Running container start"
        ./scripts/starts_ha.sh
    ;;
    dev-setup)
        get_dev
    ;;
    restart)
        echo "Killing existing container"
        pkill hass
        echo "Restarting existing container"
        pwd
        ./scripts/starts_ha.sh
    ;;
    coverage)
        rm -rf htmlcov/*
        echo "Starting coverage tests"
        coverage run -m pytest tests/
        echo "Starting coverage report"
        coverage report
        echo "Starting coverage html"
        coverage html
    ;;
esac
